# Generated by Django 4.1.6 on 2023-02-22 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oneXbet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='betting',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='league',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='league',
            name='poster',
            field=models.ImageField(null=True, upload_to='leaguesImages/'),
        ),
    ]
