# Generated by Django 4.1.6 on 2023-02-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneXbet', '0002_betting_user_league_country_league_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='draws',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='club',
            name='loses',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='club',
            name='point',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='club',
            name='wins',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
