# Generated by Django 4.1.6 on 2023-02-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneXbet', '0003_club_draws_club_loses_club_point_club_wins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='result1',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='result2',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
