# Generated by Django 4.1.6 on 2023-02-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneXbet', '0004_alter_game_result1_alter_game_result2'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
