# Generated by Django 4.1.6 on 2023-02-27 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oneXbet', '0005_game_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betting',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='club',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='clubsPoster/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='result1',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='result2',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
