# Generated by Django 4.1.6 on 2023-03-01 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oneXbet', '0006_alter_betting_user_alter_club_poster_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyAppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.PositiveIntegerField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=135)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
