# Generated by Django 4.1.6 on 2023-03-14 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oneXbet', '0007_myappuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oneXbet.league'),
        ),
        migrations.AlterField(
            model_name='betting',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oneXbet.club'),
        ),
        migrations.AlterField(
            model_name='myappuser',
            name='money',
            field=models.PositiveIntegerField(blank=True, default=5000),
        ),
    ]
