# Generated by Django 4.1.6 on 2023-03-17 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oneXbet', '0008_game_league_alter_betting_club_alter_myappuser_money'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyAppUser',
        ),
    ]
