# Generated by Django 4.1.6 on 2023-03-27 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneXbet', '0010_myappuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='betting',
            name='draw',
        ),
        migrations.RemoveField(
            model_name='betting',
            name='url',
        ),
        migrations.AlterField(
            model_name='myappuser',
            name='avatarImg',
            field=models.ImageField(blank=True, null=True, upload_to='userAvatar/'),
        ),
    ]
